import { describe, it, expect, vi, afterEach, beforeAll } from 'vitest';
import { render, screen, fireEvent, waitFor } from '@testing-library/preact';
import { createElement } from 'preact';
import { DialogComponent, PlayerDialogComponent } from '../dialog';
import { WidgetOptions } from '@/interfaces/widget-options';
import { Presentation } from '@/interfaces/presentation';

vi.mock('@/i18n', () => ({
  useI18n: vi.fn().mockReturnValue({
    t: vi.fn((key: string) => key),
  }),
}));

vi.mock('../player', () => ({
  PlayerComponent: ({ presentation }: { presentation: Presentation }) => createElement('div', {
    'data-player-url': presentation.player,
    'data-testid': 'player-component',
  }, `Player for ${presentation.title}`),
}));

vi.mock('@/components/thumbnail', () => ({
  ThumbnailComponent: ({ onClick, presentation }: {
    presentation: { title: string };
    onClick(): void;
  }) => createElement('button', {
    'data-testid': 'thumbnail-component',
    onClick,
  }, `Thumbnail: ${presentation.title}`),
}));

describe('DialogComponent', () => {
  const mockPresentation: Presentation = {
    guid: 'test-guid',
    mediaDisplayHeight: 1280,
    mediaDisplayWidth: 1920,
    player: 'https://example.com/player',
    thumbnail: {
      autoGenerated: false,
      cdnUrl: 'https://cdn.example.com/thumbnail.jpg',
      height: 200,
      url: 'https://example.com/thumbnail.jpg',
      width: 300,
    },
    title: 'Test Presentation',
  };

  const mockOptions: Partial<WidgetOptions> = {
    playbackMode: 'modal' as const,
    playIcon: {
      height: 64,
      position: 'center',
      url: 'https://example.com/play-icon.svg',
      width: 64,
    },
  } as unknown as WidgetOptions;

  beforeAll(() => {
    Object.defineProperty(HTMLElement.prototype, 'showModal', {
      value: vi.fn(),
      writable: true,
    });

    Object.defineProperty(HTMLElement.prototype, 'close', {
      value: vi.fn(),
      writable: true,
    });
  });

  afterEach(() => {
    vi.clearAllMocks();
  });

  it('should render empty string when presentation is null', () => {
    const { container } = render(createElement(DialogComponent, {
      playerParameters: {},
      presentation: null as unknown as Presentation,
      widgetOptions: mockOptions,
    }));

    expect(container.textContent).toBe('');
  });

  it('should render thumbnail component when presentation is provided', async () => {
    render(createElement(DialogComponent, {
      playerParameters: {},
      presentation: mockPresentation,
      widgetOptions: mockOptions,
    }));

    const thumbnail = await screen.findByTestId('thumbnail-component');

    expect(thumbnail).toBeInTheDocument();
    expect(thumbnail).toHaveTextContent('Thumbnail: Test Presentation');
  });

  it('should show dialog when thumbnail is clicked', async () => {
    render(createElement(DialogComponent, {
      playerParameters: {},
      presentation: mockPresentation,
      widgetOptions: mockOptions,
    }));

    const thumbnail = await screen.findByTestId('thumbnail-component');

    fireEvent.click(thumbnail);

    await waitFor(() => {
      const dialog = document.querySelector('dialog');

      expect(dialog).toBeInTheDocument();
    });
  });

  it('should render PlayerComponent in dialog', async () => {
    render(createElement(DialogComponent, {
      playerParameters: {},
      presentation: mockPresentation,
      widgetOptions: mockOptions,
    }));

    const thumbnail = await screen.findByTestId('thumbnail-component');

    fireEvent.click(thumbnail);

    await waitFor(() => {
      const playerComponent = screen.getByTestId('player-component');

      expect(playerComponent).toBeInTheDocument();
      expect(playerComponent).toHaveTextContent('Player for Test Presentation');
    });
  });

  it('should close dialog when close button is clicked', async () => {
    const closeSpy = vi.fn();

    render(createElement(DialogComponent, {
      playerParameters: {},
      presentation: mockPresentation,
      widgetOptions: mockOptions,
    }));

    const thumbnail = await screen.findByTestId('thumbnail-component');

    fireEvent.click(thumbnail);

    await waitFor(() => {
      const dialog = document.querySelector('dialog');

      expect(dialog).toBeInTheDocument();
    });

    const dialog = document.querySelector('dialog') as HTMLDialogElement;

    dialog.close = closeSpy;

    const closeButton = document.querySelector('.qc-dialog__close-button');

    expect(closeButton).toBeInTheDocument();

    fireEvent.click(closeButton!);

    expect(closeSpy).toHaveBeenCalled();
  });

  it('should close dialog when clicking on dialog backdrop', async () => {
    const closeSpy = vi.fn();

    render(createElement(DialogComponent, {
      playerParameters: {},
      presentation: mockPresentation,
      widgetOptions: mockOptions,
    }));

    const thumbnail = await screen.findByTestId('thumbnail-component');

    fireEvent.click(thumbnail);

    await waitFor(() => {
      const dialog = document.querySelector('dialog');

      expect(dialog).toBeInTheDocument();
    });

    const dialog = document.querySelector('dialog') as HTMLDialogElement;

    dialog.close = closeSpy;

    fireEvent.click(dialog);

    expect(closeSpy).toHaveBeenCalled();
  });

  it('should not close dialog when clicking on dialog content', async () => {
    const closeSpy = vi.fn();

    render(createElement(DialogComponent, {
      playerParameters: {},
      presentation: mockPresentation,
      widgetOptions: mockOptions,
    }));

    const thumbnail = await screen.findByTestId('thumbnail-component');

    fireEvent.click(thumbnail);

    await waitFor(() => {
      const dialog = document.querySelector('dialog');

      expect(dialog).toBeInTheDocument();
    });

    const dialog = document.querySelector('dialog') as HTMLDialogElement;

    dialog.close = closeSpy;

    const dialogContent = document.querySelector('.qc-dialog');

    expect(dialogContent).toBeInTheDocument();

    fireEvent.click(dialogContent!);

    expect(closeSpy).not.toHaveBeenCalled();
  });

  it('should handle dialog onClose event', async () => {
    render(createElement(DialogComponent, {
      playerParameters: {},
      presentation: mockPresentation,
      widgetOptions: mockOptions,
    }));

    const thumbnail = await screen.findByTestId('thumbnail-component');

    fireEvent.click(thumbnail);

    await waitFor(() => {
      const dialog = document.querySelector('dialog');

      expect(dialog).toBeInTheDocument();
    });

    const dialog = document.querySelector('dialog') as HTMLDialogElement;

    fireEvent(dialog, new Event('close'));

    await waitFor(() => {
      const dialogAfterClose = document.querySelector('dialog');

      expect(dialogAfterClose).not.toBeInTheDocument();
    });
  });

  it('should execute autoplay URL modification when playbackMode is inline-autoplay', async () => {
    const optionsWithAutoplay: Partial<WidgetOptions> = {
      ...mockOptions,
      playbackMode: 'inline-autoplay',
    };

    render(createElement(DialogComponent, {
      playerParameters: {},
      presentation: mockPresentation,
      widgetOptions: optionsWithAutoplay,
    }));

    const thumbnail = await screen.findByTestId('thumbnail-component');

    fireEvent.click(thumbnail);

    await waitFor(() => {
      const playerComponent = screen.getByTestId('player-component');

      expect(playerComponent).toBeInTheDocument();
    });
  });

  it('should execute autoplay URL modification when playbackMode is inline', async () => {
    const optionsWithAutoplayFalse: Partial<WidgetOptions> = {
      ...mockOptions,
      playbackMode: 'inline',
    };

    render(createElement(DialogComponent, {
      playerParameters: {},
      presentation: mockPresentation,
      widgetOptions: optionsWithAutoplayFalse,
    }));

    const thumbnail = await screen.findByTestId('thumbnail-component');

    fireEvent.click(thumbnail);

    await waitFor(() => {
      const playerComponent = screen.getByTestId('player-component');

      expect(playerComponent).toBeInTheDocument();
    });
  });

  it('should skip autoplay URL modification when playbackMode is inline-autoload', async () => {
    const optionsWithAutoplayNull: Partial<WidgetOptions> = {
      ...mockOptions,
      playbackMode: 'inline-autoload',
    };

    render(createElement(DialogComponent, {
      playerParameters: {},
      presentation: mockPresentation,
      widgetOptions: optionsWithAutoplayNull,
    }));

    const thumbnail = await screen.findByTestId('thumbnail-component');

    fireEvent.click(thumbnail);

    await waitFor(() => {
      const playerComponent = screen.getByTestId('player-component');

      expect(playerComponent).toBeInTheDocument();
    });
  });

  describe('PlayerDialogComponent', () => {
    const renderPlayerDialog = (onClose = vi.fn()) => {
      render(createElement(PlayerDialogComponent, {
        onClose,
        playerParameters: {},
        presentation: mockPresentation,
        widgetOptions: mockOptions,
      }));

      const dialog = document.querySelector('dialog')!;

      // like browsers, closing the dialog fires the `close` event
      dialog.close = vi.fn(() => dialog.dispatchEvent(new Event('close')));

      return { dialog,
        onClose };
    };

    it('should call onClose once when clicking the close button', () => {
      const { onClose } = renderPlayerDialog();

      fireEvent.click(document.querySelector('.qc-dialog__close-button')!);

      expect(onClose).toHaveBeenCalledTimes(1);
    });

    it('should call onClose once when clicking the backdrop', () => {
      const { dialog, onClose } = renderPlayerDialog();

      fireEvent.click(dialog);

      expect(onClose).toHaveBeenCalledTimes(1);
    });

    it('should name the dialog with the decoded title and the close button', () => {
      render(createElement(PlayerDialogComponent, {
        onClose: vi.fn(),
        playerParameters: {},
        presentation: {
          ...mockPresentation,
          title: 'Jane&#39;s talk',
        },
        widgetOptions: mockOptions,
      }));

      // `showModal()` is mocked, a closed dialog is hidden and has no accessible name
      document.querySelector('dialog')!.setAttribute('open', '');

      expect(screen.getByRole('dialog', { name: 'Jane\'s talk' })).toBeInTheDocument();
      expect(screen.getByRole('button', { name: 'common.Close' })).toHaveClass('qc-dialog__close-button');
    });

    it('should call onClose when the dialog is closed with the Escape key', () => {
      const { dialog, onClose } = renderPlayerDialog();

      // the browser closes the dialog itself and fires the `close` event
      fireEvent(dialog, new Event('close'));

      expect(onClose).toHaveBeenCalledTimes(1);
    });
  });
});
