import { afterEach, describe, expect, it, vi } from 'vitest';
import { fireEvent, render, screen } from '@testing-library/preact';
import { createElement } from 'preact';
import { ListItemComponent } from '../list-item';
import { MetadataType, Presentation } from '@/interfaces/presentation';

vi.mock('@/i18n', () => ({
  useI18n: vi.fn().mockReturnValue({
    getLocale: () => 'en-US',
    t: vi.fn((key: string, options?: Record<string, string>) => (options?.title ? `${key}: ${options.title}` : key)),
  }),
}));

describe('ListItemComponent', () => {
  const presentation: Presentation = {
    duration: 65_000,
    guid: 'guid',
    publisher: {
      guid: 'u',
      name: 'Jane Doe',
      username: 'jane',
    },
    thumbnail: {
      autoGenerated: false,
      cdnUrl: 'https://cdn.example.com/thumb.jpg',
      height: 180,
      url: 'https://example.com/thumb.jpg',
      width: 320,
    },
    title: 'My presentation',
  };

  const renderItem = (props: Record<string, unknown> = {}) => render(createElement(ListItemComponent, {
    id: 'item',
    item: {
      info: { bottom: [{ field: 'title' }] },
      showDurationOverlay: false,
    },
    onClick: vi.fn(),
    presentation,
    ...props,
  }));

  it('should render the thumbnail and the info fields', () => {
    const { container } = renderItem();

    expect(container.innerHTML).toMatchInlineSnapshot(`"<div id="item" class="qc-list-item"><div class="qc-list-item__body"><button type="button" class="qc-thumbnail"><span class="qc-sr-only">common.PLAY_PRESENTATION: My presentation</span><img class="qc-thumbnail__image" src="https://cdn.example.com/thumb.jpg" alt="" loading="lazy"><svg class="qc-thumbnail__play-button qc-thumbnail__play-button--default" aria-hidden="true"><use href="#icon-play"></use></svg></button></div><dl class="qc-list-item__info qc-list-item__info--bottom"><div id="item-bottom-0" class="qc-list-item__field" data-field="title"><dt class="qc-list-item__label qc-sr-only">list.fields.title</dt> <dd class="qc-list-item__value">My presentation</dd></div></dl></div>"`);
  });

  describe('accessibility', () => {
    it('should name the button with the play text only, and describe it with the other fields', () => {
      renderItem({
        item: {
          info: {
            bottom: [{ field: 'title' }, { field: 'publisher' }],
            top: [{ field: 'duration' }],
          },
          showDurationOverlay: true,
        },
      });

      // the title is part of the name, so it is not repeated in the description
      expect(screen.getByRole('button', {
        description: 'list.fields.duration 01:05 list.fields.publisher Jane Doe',
        name: 'common.PLAY_PRESENTATION: My presentation',
      })).toBeInTheDocument();
    });

    it('should describe the duration of the badge when it is not an info field', () => {
      renderItem({
        item: {
          info: { bottom: [{ field: 'title' }] },
          showDurationOverlay: true,
        },
      });

      expect(screen.getByRole('button')).toHaveAttribute('aria-describedby', 'item-duration');
      expect(screen.getByRole('button', { description: 'list.fields.duration 01:05' })).toBeInTheDocument();
    });

    it('should not have a description when only the title is shown', () => {
      renderItem();

      expect(screen.getByRole('button')).not.toHaveAttribute('aria-describedby');
    });

    it('should decode the HTML entities of the title in the name', () => {
      renderItem({
        presentation: {
          ...presentation,
          title: 'Jane&#39;s talk',
        },
      });

      expect(screen.getByRole('button', { name: 'common.PLAY_PRESENTATION: Jane\'s talk' })).toBeInTheDocument();
    });
  });

  it('should render the fields as description lists', () => {
    const { container } = renderItem({
      item: {
        info: {
          bottom: [
            { field: 'title' },
            { field: 'publisher' },
          ],
        },
        showDurationOverlay: false,
      },
    });

    const list = container.querySelector('dl.qc-list-item__info--bottom')!;
    const groups = Array.from(list.children);

    // `dl > div > dt + dd`, a term for each value
    expect(groups.map(({ tagName }) => tagName)).toEqual(['DIV', 'DIV']);
    groups.forEach((group) => {
      expect(Array.from(group.children, ({ tagName }) => tagName)).toEqual(['DT', 'DD']);
    });
    expect(container.querySelector('.qc-list-item__body')!.tagName).toBe('DIV');
  });

  it('should render the fields in their slots, in order', () => {
    const { container } = renderItem({
      item: {
        info: {
          left: [{ field: 'publisher' }],
          right: [{ field: 'duration' }],
          top: [{ field: 'title' }, { field: 'publisher' }],
        },
        showDurationOverlay: false,
      },
    });

    const slotFields = (slot: string) => Array.from(container.querySelectorAll(`.qc-list-item__info--${slot} [data-field]`))
      .map((el) => el.getAttribute('data-field'));

    expect(slotFields('top')).toEqual(['title', 'publisher']);
    expect(slotFields('left')).toEqual(['publisher']);
    expect(slotFields('right')).toEqual(['duration']);
    expect(container.querySelector('.qc-list-item__info--bottom')).toBeNull();
  });

  it('should skip fields without a value', () => {
    const { container } = renderItem({
      item: {
        info: { bottom: [{ field: 'summary' }, { field: 'title' }] },
        showDurationOverlay: false,
      },
    });

    expect(container.querySelectorAll('[data-field]')).toHaveLength(1);
  });

  it('should render the labels', () => {
    const { container } = renderItem({
      item: {
        info: {
          bottom: [
            { field: 'title' },
            {
              field: 'publisher',
              label: true,
            },
            {
              field: 'duration',
              label: 'Length',
            },
            {
              field: 'title',
              label: false,
            },
          ],
        },
        showDurationOverlay: false,
      },
    });

    const labels = Array.from(container.querySelectorAll('.qc-list-item__label:not(.qc-sr-only)')).map((el) => el.textContent?.trim());

    expect(labels).toEqual(['list.fields.publisher', 'Length']);
  });

  it('should show the default label when unset, except for the title and the summary', () => {
    const { container } = renderItem({
      item: {
        info: {
          bottom: [
            { field: 'title' },
            { field: 'summary' },
            { field: 'publisher' },
            { field: 'md-department' },
          ],
        },
        showDurationOverlay: false,
      },
      presentation: {
        ...presentation,
        metadata: [
          {
            guid: 'md-department',
            title: 'Department',
            type: MetadataType.Text,
            value: 'Sales',
          },
        ],
        summary: 'A summary',
      },
    });

    const labelOf = (field: string) => container.querySelector(`[data-field="${field}"] .qc-list-item__label:not(.qc-sr-only)`)?.textContent?.trim();
    const hiddenTermOf = (field: string) => container.querySelector(`[data-field="${field}"] dt.qc-sr-only`)?.textContent?.trim();

    expect(labelOf('title')).toBeUndefined();
    expect(labelOf('summary')).toBeUndefined();
    expect(labelOf('publisher')).toBe('list.fields.publisher');
    // metadata fields use the metadata title as default label
    expect(labelOf('md-department')).toBe('Department');
    // a hidden label is still the term of the value, for the screen readers
    expect(hiddenTermOf('title')).toBe('list.fields.title');
    expect(hiddenTermOf('summary')).toBe('list.fields.summary');
  });

  it('should hide the label of any field with label: false and show it for title/summary with label: true', () => {
    const { container } = renderItem({
      item: {
        info: {
          bottom: [
            {
              field: 'title',
              label: true,
            },
            {
              field: 'publisher',
              label: false,
            },
          ],
        },
        showDurationOverlay: false,
      },
    });

    const labels = Array.from(container.querySelectorAll('.qc-list-item__label:not(.qc-sr-only)')).map((el) => el.textContent?.trim());

    expect(labels).toEqual(['list.fields.title']);
  });

  it('should render the html of Markdown metadata values', () => {
    const { container } = renderItem({
      item: {
        info: { bottom: [{ field: 'md-description' }] },
        showDurationOverlay: false,
      },
      presentation: {
        ...presentation,
        metadata: [
          {
            guid: 'md-description',
            html: '<p>A <strong>bold</strong> <a href="https://example.com">link</a></p>\n',
            title: 'Description',
            type: MetadataType.LargeText,
            value: 'A **bold** [link](https://example.com)',
          },
        ],
      },
    });

    const value = container.querySelector('[data-field="md-description"] .qc-list-item__value--html')!;

    expect(value.innerHTML).toBe('A <strong>bold</strong> <a href="https://example.com" target="_blank" rel="noopener noreferrer">link</a>');
    // the label stays inline with the value
    expect(screen.getByRole('button', { description: 'Description A bold link' })).toBeInTheDocument();
  });

  it('should render the duration overlay', () => {
    const { container } = renderItem({
      item: {
        info: {},
        showDurationOverlay: true,
      },
    });

    expect(container.querySelector('.qc-list-item__duration')?.textContent).toBe('01:05');
  });

  it('should render a custom play icon', () => {
    const { container } = renderItem({ playIconUrl: 'https://example.com/play.svg' });

    expect(container.querySelector('img.qc-thumbnail__play-button')?.getAttribute('src')).toBe('https://example.com/play.svg');
  });

  it('should apply the per-field style', () => {
    const { container } = renderItem({
      metadataStyle: {
        title: {
          color: 'red',
          fontFamily: 'Orbitron, sans-serif',
          hoverLabelColor: 'green',
          letterSpacing: '.04em',
          lineClamp: 2,
          padding: '4px 8px',
          textTransform: 'uppercase',
        },
      },
    });

    const field = container.querySelector<HTMLElement>('[data-field="title"]')!;

    expect(field.style.getPropertyValue('--qc-lw-field-color')).toBe('red');
    expect(field.style.getPropertyValue('--qc-lw-field-hover-label-color')).toBe('green');
    expect(field.style.getPropertyValue('--qc-lw-field-font-family')).toBe('Orbitron, sans-serif');
    expect(field.style.getPropertyValue('--qc-lw-field-letter-spacing')).toBe('.04em');
    expect(field.style.getPropertyValue('--qc-lw-field-text-transform')).toBe('uppercase');
    expect(field.style.getPropertyValue('--qc-lw-field-padding')).toBe('4px 8px');
    expect(field.style.getPropertyValue('--qc-lw-field-line-clamp')).toBe('2');
    expect(field.classList.contains('qc-list-item__field--clamp')).toBe(true);
  });

  it('should only clamp the fields with a lineClamp', () => {
    const { container } = renderItem({
      item: {
        info: { bottom: [{ field: 'title' }, { field: 'publisher' }] },
        showDurationOverlay: false,
      },
      metadataStyle: { publisher: { color: 'red' } },
    });

    expect(container.querySelectorAll('.qc-list-item__field--clamp')).toHaveLength(0);
  });

  describe('click', () => {
    afterEach(() => {
      globalThis.getSelection()?.removeAllRanges();
    });

    const selectText = (element: Element) => {
      const range = document.createRange();

      range.selectNodeContents(element);
      globalThis.getSelection()!.removeAllRanges();
      globalThis.getSelection()!.addRange(range);
    };

    it('should call onClick with the presentation when clicking anywhere on the item', () => {
      const onClick = vi.fn();
      const { container } = renderItem({ onClick });

      fireEvent.click(container.querySelector('[data-field="title"]')!, { detail: 1 });

      expect(onClick).toHaveBeenCalledWith(presentation);
    });

    it('should make the thumbnail the play button, for the keyboard and the screen readers', () => {
      const onClick = vi.fn();

      renderItem({ onClick });

      const buttons = screen.getAllByRole('button');

      expect(buttons).toHaveLength(1);
      expect(buttons[0]).toHaveClass('qc-thumbnail');

      // a keyboard activation fires a click with `detail` 0
      fireEvent.click(buttons[0], { detail: 0 });

      expect(onClick).toHaveBeenCalledWith(presentation);
    });

    it('should not play when the click ends a text selection in the item, so the text can be copied', () => {
      const onClick = vi.fn();
      const { container } = renderItem({ onClick });
      const title = container.querySelector('[data-field="title"]')!;

      selectText(title);
      fireEvent.click(title, { detail: 1 });

      expect(onClick).not.toHaveBeenCalled();
    });

    it('should play with the keyboard even when some text is selected', () => {
      const onClick = vi.fn();
      const { container } = renderItem({ onClick });

      selectText(container.querySelector('[data-field="title"]')!);
      fireEvent.click(screen.getByRole('button'), { detail: 0 });

      expect(onClick).toHaveBeenCalledTimes(1);
    });

    it('should play when the selected text is outside of the item', () => {
      const onClick = vi.fn();
      const outside = document.createElement('p');

      outside.textContent = 'elsewhere';
      document.body.append(outside);

      const { container } = renderItem({ onClick });

      selectText(outside);
      fireEvent.click(container.querySelector('[data-field="title"]')!, { detail: 1 });

      expect(onClick).toHaveBeenCalledTimes(1);
      outside.remove();
    });

    it('should not play when clicking a link of a Markdown value, with the mouse or the keyboard', () => {
      const onClick = vi.fn();
      const { container } = renderItem({
        item: {
          info: { bottom: [{ field: 'md-description' }] },
          showDurationOverlay: false,
        },
        onClick,
        presentation: {
          ...presentation,
          metadata: [
            {
              guid: 'md-description',
              html: '<p>see <a href="https://example.com"><em>the docs</em></a></p>',
              title: 'Description',
              type: MetadataType.LargeText,
            },
          ],
        },
      });

      fireEvent.click(container.querySelector('a em')!, { detail: 1 });
      fireEvent.click(container.querySelector('a')!, { detail: 0 });

      expect(onClick).not.toHaveBeenCalled();
    });
  });
});
