import { describe, expect, it, vi } from 'vitest';
import { fireEvent, render, screen } from '@testing-library/preact';
import { createElement } from 'preact';
import { ListItemComponent } from '../list-item';
import { MetadataType, Presentation } from '@/interfaces/presentation';

vi.mock('@/i18n', () => ({
  useI18n: vi.fn().mockReturnValue({
    getLocale: () => 'en-US',
    t: vi.fn((key: string, options?: Record<string, string>) => (options?.title ? `${key}: ${options.title}` : key)),
  }),
}));

describe('ListItemComponent', () => {
  const presentation: Presentation = {
    duration: 65_000,
    guid: 'guid',
    publisher: {
      guid: 'u',
      name: 'Jane Doe',
      username: 'jane',
    },
    thumbnail: {
      autoGenerated: false,
      cdnUrl: 'https://cdn.example.com/thumb.jpg',
      height: 180,
      url: 'https://example.com/thumb.jpg',
      width: 320,
    },
    title: 'My presentation',
  };

  const renderItem = (props: Record<string, unknown> = {}) => render(createElement(ListItemComponent, {
    idPrefix: 'item',
    item: {
      info: { bottom: [{ field: 'title' }] },
      showDurationOverlay: false,
    },
    onClick: vi.fn(),
    presentation,
    ...props,
  }));

  it('should render the thumbnail and the info fields', () => {
    const { container } = renderItem();

    expect(container.innerHTML).toMatchInlineSnapshot(`"<button type="button" class="qc-list-item" aria-label="common.PLAY_PRESENTATION: My presentation"><span class="qc-list-item__body"><span class="qc-list-item__thumbnail"><img class="qc-list-item__image" src="https://cdn.example.com/thumb.jpg" alt="" loading="lazy"><svg class="qc-list-item__play-button qc-list-item__play-button--default" aria-hidden="true"><use href="#icon-play"></use></svg></span></span><span class="qc-list-item__info qc-list-item__info--bottom"><span id="item-bottom-0" class="qc-list-item__field" data-field="title"><span class="qc-list-item__field-content"><span class="qc-list-item__value">My presentation</span></span></span></span></button>"`);
  });

  describe('accessibility', () => {
    it('should name the button with the play text only, and describe it with the other fields', () => {
      renderItem({
        item: {
          info: {
            bottom: [{ field: 'title' }, { field: 'publisher' }],
            top: [{ field: 'duration' }],
          },
          showDurationOverlay: true,
        },
      });

      // the title is part of the name, so it is not repeated in the description
      expect(screen.getByRole('button', {
        description: 'list.fields.duration 01:05 list.fields.publisher Jane Doe',
        name: 'common.PLAY_PRESENTATION: My presentation',
      })).toBeInTheDocument();
    });

    it('should describe the duration of the badge when it is not an info field', () => {
      renderItem({
        item: {
          info: { bottom: [{ field: 'title' }] },
          showDurationOverlay: true,
        },
      });

      expect(screen.getByRole('button')).toHaveAttribute('aria-describedby', 'item-duration');
      expect(screen.getByRole('button', { description: 'list.fields.duration 01:05' })).toBeInTheDocument();
    });

    it('should not have a description when only the title is shown', () => {
      renderItem();

      expect(screen.getByRole('button')).not.toHaveAttribute('aria-describedby');
    });

    it('should decode the HTML entities of the title in the name', () => {
      renderItem({
        presentation: {
          ...presentation,
          title: 'Jane&#39;s talk',
        },
      });

      expect(screen.getByRole('button', { name: 'common.PLAY_PRESENTATION: Jane\'s talk' })).toBeInTheDocument();
    });
  });

  it('should render the fields in their slots, in order', () => {
    const { container } = renderItem({
      item: {
        info: {
          left: [{ field: 'publisher' }],
          right: [{ field: 'duration' }],
          top: [{ field: 'title' }, { field: 'publisher' }],
        },
        showDurationOverlay: false,
      },
    });

    const slotFields = (slot: string) => Array.from(container.querySelectorAll(`.qc-list-item__info--${slot} [data-field]`))
      .map((el) => el.getAttribute('data-field'));

    expect(slotFields('top')).toEqual(['title', 'publisher']);
    expect(slotFields('left')).toEqual(['publisher']);
    expect(slotFields('right')).toEqual(['duration']);
    expect(container.querySelector('.qc-list-item__info--bottom')).toBeNull();
  });

  it('should skip fields without a value', () => {
    const { container } = renderItem({
      item: {
        info: { bottom: [{ field: 'summary' }, { field: 'title' }] },
        showDurationOverlay: false,
      },
    });

    expect(container.querySelectorAll('[data-field]')).toHaveLength(1);
  });

  it('should render the labels', () => {
    const { container } = renderItem({
      item: {
        info: {
          bottom: [
            { field: 'title' },
            {
              field: 'publisher',
              label: true,
            },
            {
              field: 'duration',
              label: 'Length',
            },
            {
              field: 'title',
              label: false,
            },
          ],
        },
        showDurationOverlay: false,
      },
    });

    const labels = Array.from(container.querySelectorAll('.qc-list-item__label')).map((el) => el.textContent?.trim());

    expect(labels).toEqual(['list.fields.publisher', 'Length']);
  });

  it('should show the default label when unset, except for the title and the summary', () => {
    const { container } = renderItem({
      item: {
        info: {
          bottom: [
            { field: 'title' },
            { field: 'summary' },
            { field: 'publisher' },
            { field: 'md-department' },
          ],
        },
        showDurationOverlay: false,
      },
      presentation: {
        ...presentation,
        metadata: [
          {
            guid: 'md-department',
            title: 'Department',
            type: MetadataType.Text,
            value: 'Sales',
          },
        ],
        summary: 'A summary',
      },
    });

    const labelOf = (field: string) => container.querySelector(`[data-field="${field}"] .qc-list-item__label`)?.textContent?.trim();

    expect(labelOf('title')).toBeUndefined();
    expect(labelOf('summary')).toBeUndefined();
    expect(labelOf('publisher')).toBe('list.fields.publisher');
    // metadata fields use the metadata title as default label
    expect(labelOf('md-department')).toBe('Department');
  });

  it('should hide the label of any field with label: false and show it for title/summary with label: true', () => {
    const { container } = renderItem({
      item: {
        info: {
          bottom: [
            {
              field: 'title',
              label: true,
            },
            {
              field: 'publisher',
              label: false,
            },
          ],
        },
        showDurationOverlay: false,
      },
    });

    const labels = Array.from(container.querySelectorAll('.qc-list-item__label')).map((el) => el.textContent?.trim());

    expect(labels).toEqual(['list.fields.title']);
  });

  it('should render the duration overlay', () => {
    const { container } = renderItem({
      item: {
        info: {},
        showDurationOverlay: true,
      },
    });

    expect(container.querySelector('.qc-list-item__duration')?.textContent).toBe('01:05');
  });

  it('should render a custom play icon', () => {
    const { container } = renderItem({ playIconUrl: 'https://example.com/play.svg' });

    expect(container.querySelector('img.qc-list-item__play-button')?.getAttribute('src')).toBe('https://example.com/play.svg');
  });

  it('should apply the per-field style', () => {
    const { container } = renderItem({
      metadataStyle: {
        title: {
          color: 'red',
          fontFamily: 'Orbitron, sans-serif',
          hoverLabelColor: 'green',
          letterSpacing: '.04em',
          lineClamp: 2,
          padding: '4px 8px',
          textTransform: 'uppercase',
        },
      },
    });

    const field = container.querySelector<HTMLElement>('[data-field="title"]')!;

    expect(field.style.getPropertyValue('--qc-lw-field-color')).toBe('red');
    expect(field.style.getPropertyValue('--qc-lw-field-hover-label-color')).toBe('green');
    expect(field.style.getPropertyValue('--qc-lw-field-font-family')).toBe('Orbitron, sans-serif');
    expect(field.style.getPropertyValue('--qc-lw-field-letter-spacing')).toBe('.04em');
    expect(field.style.getPropertyValue('--qc-lw-field-text-transform')).toBe('uppercase');
    expect(field.style.getPropertyValue('--qc-lw-field-padding')).toBe('4px 8px');
    expect(field.style.getPropertyValue('--qc-lw-field-line-clamp')).toBe('2');
    expect(field.classList.contains('qc-list-item__field--clamp')).toBe(true);
  });

  it('should only clamp the fields with a lineClamp', () => {
    const { container } = renderItem({
      item: {
        info: { bottom: [{ field: 'title' }, { field: 'publisher' }] },
        showDurationOverlay: false,
      },
      metadataStyle: { publisher: { color: 'red' } },
    });

    expect(container.querySelectorAll('.qc-list-item__field--clamp')).toHaveLength(0);
  });

  it('should call onClick with the presentation when clicking anywhere on the item', () => {
    const onClick = vi.fn();
    const { container } = renderItem({ onClick });

    fireEvent.click(container.querySelector('[data-field="title"]')!);

    expect(onClick).toHaveBeenCalledWith(presentation);
  });
});
