import { describe, expect, it } from 'vitest';
import { render } from '@testing-library/preact';
import { createElement } from 'preact';
import { ThumbnailMediaComponent } from '../thumbnail-media';
import { Presentation } from '@/interfaces/presentation';

describe('ThumbnailMediaComponent', () => {
  const presentation: Presentation = {
    guid: 'guid',
    thumbnail: {
      autoGenerated: false,
      cdnUrl: 'https://cdn.example.com/thumb.jpg',
      height: 180,
      url: 'https://example.com/thumb.jpg',
      width: 320,
    },
    title: 'My presentation',
  };

  const renderMedia = (props: Record<string, unknown> = {}) => render(createElement(ThumbnailMediaComponent, {
    block: 'qc-block',
    presentation,
    ...props,
  })).container;

  it('should render the image and the default play icon, without an interactive element', () => {
    expect(renderMedia().innerHTML).toMatchInlineSnapshot(`"<img class="qc-block__image" src="https://cdn.example.com/thumb.jpg" alt=""><svg class="qc-block__play-button qc-block__play-button--default" aria-hidden="true"><use href="#icon-play"></use></svg>"`);
  });

  it('should name the classes after the block of the parent', () => {
    const container = renderMedia({ block: 'qc-list-item' });

    expect(container.querySelector('img')).toHaveClass('qc-list-item__image');
    expect(container.querySelector('svg')).toHaveClass('qc-list-item__play-button', 'qc-list-item__play-button--default');
  });

  it('should fall back to the thumbnail url when there is no CDN url', () => {
    const container = renderMedia({
      presentation: {
        ...presentation,
        thumbnail: {
          ...presentation.thumbnail!,
          cdnUrl: undefined,
        },
      },
    });

    expect(container.querySelector('.qc-block__image')).toHaveAttribute('src', 'https://example.com/thumb.jpg');
  });

  it('should render a custom play icon, decorative like the default one', () => {
    const container = renderMedia({ playIconUrl: 'https://example.com/play.svg' });
    const icon = container.querySelector('.qc-block__play-button')!;

    expect(icon.tagName).toBe('IMG');
    expect(icon).toHaveAttribute('src', 'https://example.com/play.svg');
    expect(icon).toHaveAttribute('alt', '');
    expect(icon).not.toHaveClass('qc-block__play-button--default');
    expect(container.querySelector('svg')).toBeNull();
  });

  it('should only set the loading attribute when given', () => {
    expect(renderMedia().querySelector('.qc-block__image')).not.toHaveAttribute('loading');
    expect(renderMedia({ loading: 'lazy' }).querySelector('.qc-block__image')).toHaveAttribute('loading', 'lazy');
  });
});
