import { describe, it, expect, vi, afterEach, beforeEach } from 'vitest';
import { render, screen, fireEvent } from '@testing-library/preact';
import { createElement } from 'preact';
import { ThumbnailComponent } from '../thumbnail';
import { WidgetOptions } from '@/interfaces/widget-options';
import { Presentation } from '@/interfaces/presentation';
import { ConfigurationService } from '@/services/configuration.service';

vi.mock('@/i18n', () => ({
  useI18n: vi.fn().mockReturnValue({
    t: vi.fn((key: string) => key),
  }),
}));

describe('ThumbnailComponent', () => {
  const mockPresentation: Presentation = {
    guid: 'test-guid',
    player: 'https://example.com/player',
    thumbnail: {
      autoGenerated: false,
      cdnUrl: 'https://cdn.example.com/thumbnail.jpg',
      height: 200,
      url: 'https://example.com/thumbnail.jpg',
      width: 300,
    },
    title: 'Test Presentation',
  };

  const configurationService = new ConfigurationService();
  const mockConfiguration = configurationService.createConfiguration({
    guid: 'test-guid',
    host: 'https://example.com',
    selector: '#widget-container',
  });

  const mockOnClick = vi.fn();

  beforeEach(() => {
    vi.clearAllMocks();
    document.head.innerHTML = '';
  });

  afterEach(() => {
    vi.clearAllMocks();
  });

  describe('Rendering', () => {
    it('should render thumbnail button with image', () => {
      const { container } = render(createElement(ThumbnailComponent, {
        onClick: mockOnClick,
        presentation: mockPresentation,
        widgetOptions: mockConfiguration.widgetOptions as WidgetOptions,
      }));

      const button = container.querySelector('button');

      expect(button).toHaveClass('qc-thumbnail');

      const image = container.querySelector('.qc-thumbnail__image');

      expect(image).toHaveAttribute('src', 'https://cdn.example.com/thumbnail.jpg');
    });

    it('should use thumbnail url when cdnUrl is not available', () => {
      const presentationWithoutCdn = {
        ...mockPresentation,
        thumbnail: {
          ...mockPresentation.thumbnail!,
          cdnUrl: undefined,
        },
      };

      const { container } = render(createElement(ThumbnailComponent, {
        onClick: mockOnClick,
        presentation: presentationWithoutCdn,
        widgetOptions: mockConfiguration.widgetOptions as WidgetOptions,
      }));

      const image = container.querySelector('.qc-thumbnail__image');

      expect(image).toHaveAttribute('src', 'https://example.com/thumbnail.jpg');
    });
  });

  describe('Play Icon', () => {
    it('should render default play icon when no custom play icon is provided', () => {
      const { container } = render(createElement(ThumbnailComponent, {
        onClick: mockOnClick,
        presentation: mockPresentation,
        widgetOptions: {
          ...mockConfiguration.widgetOptions as WidgetOptions,
          playIconUrl: undefined,
        },
      }));

      const playIcon = container.querySelector('.qc-thumbnail__play-button--default');

      expect(playIcon).toHaveClass('qc-thumbnail__play-button');
    });

    it('should render custom play icon image when provided in options', () => {
      const widgetOptions = {
        ...mockConfiguration.widgetOptions as WidgetOptions,
        playIconUrl: 'https://example.com/custom-play-icon.png',
      } as WidgetOptions;

      const { container } = render(createElement(ThumbnailComponent, {
        onClick: mockOnClick,
        presentation: mockPresentation,
        widgetOptions,
      }));

      const playIconImage = container.querySelector('.qc-thumbnail__play-button');

      expect(playIconImage).toHaveAttribute('src', 'https://example.com/custom-play-icon.png');
    });
  });

  describe('Click Interaction', () => {
    it('should call onClick handler when thumbnail is clicked', () => {
      render(createElement(ThumbnailComponent, {
        onClick: mockOnClick,
        presentation: mockPresentation,
        widgetOptions: mockConfiguration.widgetOptions as WidgetOptions,
      }));

      const button = screen.getByRole('button');

      fireEvent.click(button);

      expect(mockOnClick).toHaveBeenCalledTimes(1);
    });

    it('should call onClick handler multiple times when clicked multiple times', () => {
      render(createElement(ThumbnailComponent, {
        onClick: mockOnClick,
        presentation: mockPresentation,
        widgetOptions: mockConfiguration.widgetOptions as WidgetOptions,
      }));

      const button = screen.getByRole('button');

      fireEvent.click(button);
      fireEvent.click(button);
      fireEvent.click(button);

      expect(mockOnClick).toHaveBeenCalledTimes(3);
    });

    it('should call onThumbnailClick from widgetOptions if provided', () => {
      const mockOnThumbnailClick = vi.fn();
      const widgetOptions: Partial<WidgetOptions> = {
        ...mockConfiguration.widgetOptions as WidgetOptions,
        onThumbnailClick: mockOnThumbnailClick,
      };

      render(createElement(ThumbnailComponent, {
        onClick: mockOnClick,
        presentation: mockPresentation,
        widgetOptions,
      }));

      const button = screen.getByRole('button');

      fireEvent.click(button);

      expect(mockOnThumbnailClick).toHaveBeenCalledTimes(1);
      expect(mockOnThumbnailClick).toHaveBeenCalledWith(mockPresentation);
      expect(mockOnClick).not.toHaveBeenCalled();
    });
  });

  describe('Accessibility', () => {
    it('should have proper button type attribute', () => {
      render(createElement(ThumbnailComponent, {
        onClick: mockOnClick,
        presentation: mockPresentation,
        widgetOptions: {
          ...mockConfiguration.widgetOptions as WidgetOptions,
          playIcon: {
            height: 100,
            position: 'bottom-left',
            width: 100,
          },
        } as WidgetOptions,
      }));

      const button = screen.getByRole('button');

      expect(button).toHaveAttribute('type', 'button');
    });

    it('should have descriptive alt text for the button', () => {
      const { container } = render(createElement(ThumbnailComponent, {
        onClick: mockOnClick,
        presentation: mockPresentation,
        widgetOptions: {
          ...mockConfiguration.widgetOptions as WidgetOptions,
          playIcon: {
            height: 100,
            position: 'bottom-left',
            width: 100,
          },
        } as WidgetOptions,
      }));

      const span = container.querySelector('span')!;

      expect(span.innerHTML).toEqual('common.PLAY_PRESENTATION');
    });

    it('should have descriptive alt text for thumbnail image', () => {
      render(createElement(ThumbnailComponent, {
        onClick: mockOnClick,
        presentation: mockPresentation,
        widgetOptions: {
          ...mockConfiguration.widgetOptions as WidgetOptions,
          playIcon: {
            height: 100,
            position: 'bottom-left',
            width: 100,
          },
        } as WidgetOptions,
      }));

      const image = screen.getAllByRole('img')[0];

      expect(image).toHaveAttribute('alt', '');
    });

    it('should have alt text for custom play icon', () => {
      const widgetOptions = {
        ...mockConfiguration.widgetOptions as WidgetOptions,
        playIconUrl: 'https://example.com/custom-play-icon.png',
      } as WidgetOptions;

      render(createElement(ThumbnailComponent, {
        onClick: mockOnClick,
        presentation: mockPresentation,
        widgetOptions,
      }));

      const playIcon = screen.getAllByRole('img')[1];

      expect(playIcon).toHaveAttribute('alt', '');
    });
  });

  // used by the list widget items, which handle the click themselves
  describe('Reuse', () => {
    const renderReused = (props: Record<string, unknown> = {}) => render(createElement(ThumbnailComponent, {
      block: 'qc-list-item',
      class: 'qc-list-item__thumbnail',
      presentation: mockPresentation,
      widgetOptions: {},
      ...props,
    })).container;

    it('should render the presentation widget classes by default', () => {
      const { container } = render(createElement(ThumbnailComponent, {
        onClick: mockOnClick,
        presentation: mockPresentation,
        widgetOptions: {},
      }));

      expect(container.querySelector('button')).toHaveClass('qc-thumbnail');
      expect(container.querySelector('img')).toHaveClass('qc-thumbnail__image');
      expect(container.querySelector('svg')).toHaveClass('qc-thumbnail__play-button', 'qc-thumbnail__play-button--default');
    });

    it('should name the classes after the given class and block', () => {
      const container = renderReused({ widgetOptions: { playIconUrl: 'https://example.com/play.svg' } });

      expect(container.querySelector('button')).toHaveClass('qc-list-item__thumbnail');
      expect(container.querySelector('button')).not.toHaveClass('qc-thumbnail');
      expect(container.querySelector('.qc-list-item__image')).toBeInTheDocument();
      expect(container.querySelector('img.qc-list-item__play-button')).toHaveAttribute('src', 'https://example.com/play.svg');
    });

    it('should only set the loading attribute of the image when given', () => {
      expect(renderReused().querySelector('.qc-list-item__image')).not.toHaveAttribute('loading');
      document.body.innerHTML = '';
      expect(renderReused({ loading: 'lazy' }).querySelector('.qc-list-item__image')).toHaveAttribute('loading', 'lazy');
    });

    it('should render its children, e.g. the duration badge', () => {
      const container = renderReused({ children: createElement('span', { class: 'qc-list-item__duration' }, '01:05') });

      expect(container.querySelector('button .qc-list-item__duration')?.textContent).toBe('01:05');
    });

    it('should be described by the given elements', () => {
      const description = document.createElement('span');

      description.id = 'description';
      description.textContent = 'Published by Jane Doe';
      document.body.append(description);

      renderReused({ describedBy: 'description' });

      expect(screen.getByRole('button', {
        description: 'Published by Jane Doe',
        name: 'common.PLAY_PRESENTATION',
      })).toBeInTheDocument();
    });

    it('should leave the click to its parent when there is no onClick', () => {
      const parentClick = vi.fn();
      const container = renderReused();

      container.addEventListener('click', parentClick);
      fireEvent.click(container.querySelector('button')!);

      expect(parentClick).toHaveBeenCalledTimes(1);
    });
  });
});
